"""Initial schema — mirrors src/database/prisma/schema.prisma exactly.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-30

NOTE: this migration was authored by hand against db/models.py rather than
generated by `alembic revision --autogenerate`, because this development
sandbox has no live Postgres connection to autogenerate against. Before
running this in a real environment, run:

    alembic revision --autogenerate -m "verify_initial_schema"

against a throwaway database and diff the result against this file — it
should be empty (no-op) if models.py and this migration agree. See
PORTING_NOTES.md.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = postgresql.ENUM("USER", "ADMIN", "SUPERADMIN", name="role", create_type=False)
wallet_status_enum = postgresql.ENUM(
    "PENDING_REVIEW", "APPROVED", "REJECTED", "SUSPENDED", "RETIRED",
    name="walletstatus", create_type=False,
)
risk_profile_enum = postgresql.ENUM(
    "CONSERVATIVE", "BALANCED", "AGGRESSIVE", name="riskprofile", create_type=False
)
trade_side_enum = postgresql.ENUM("BUY", "SELL", name="tradeside", create_type=False)
trade_source_enum = postgresql.ENUM("MANUAL", "AUTO_SIGNAL", name="tradesource", create_type=False)
trade_status_enum = postgresql.ENUM(
    "PENDING", "SUBMITTED", "CONFIRMED", "FAILED", "CANCELLED",
    name="tradestatus", create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    for e in (
        role_enum,
        wallet_status_enum,
        risk_profile_enum,
        trade_side_enum,
        trade_source_enum,
        trade_status_enum,
    ):
        e.create(bind, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("telegram_id", sa.String(), nullable=False, unique=True),
        sa.Column("role", role_enum, nullable=False, server_default="USER"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("encrypted_wallet_key", sa.String(), nullable=True),
        sa.Column("wallet_public_key", sa.String(), nullable=True),
    )

    op.create_table(
        "whale_wallets",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("address", sa.String(), nullable=False, unique=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("status", wallet_status_enum, nullable=False, server_default="PENDING_REVIEW"),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"),
        sa.Column("score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("roi_30d", sa.Float(), nullable=True),
        sa.Column("pnl_usd_30d", sa.Float(), nullable=True),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("avg_hold_minutes", sa.Float(), nullable=True),
        sa.Column("avg_position_usd", sa.Float(), nullable=True),
        sa.Column("trade_frequency_7d", sa.Float(), nullable=True),
        sa.Column("wallet_age_days", sa.Integer(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("trade_success_rate", sa.Float(), nullable=True),
        sa.Column("liquidity_preference", sa.String(), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("added_by_admin_id", sa.String(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_whale_wallets_status", "whale_wallets", ["status"])
    op.create_index("ix_whale_wallets_score", "whale_wallets", ["score"])

    op.create_table(
        "wallet_events",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("wallet_id", sa.String(), sa.ForeignKey("whale_wallets.id"), nullable=False),
        sa.Column("token_mint", sa.String(), nullable=False),
        sa.Column("side", trade_side_enum, nullable=False),
        sa.Column("amount_tokens", sa.Float(), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column("tx_signature", sa.String(), nullable=False, unique=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index(
        "ix_wallet_events_token_mint_observed_at", "wallet_events", ["token_mint", "observed_at"]
    )
    op.create_index(
        "ix_wallet_events_wallet_id_observed_at", "wallet_events", ["wallet_id", "observed_at"]
    )

    op.create_table(
        "signals",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("token_mint", sa.String(), nullable=False),
        sa.Column("token_symbol", sa.String(), nullable=True),
        sa.Column("wallet_count", sa.Integer(), nullable=False),
        sa.Column("total_capital_usd", sa.Float(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("entry_zone_low", sa.Float(), nullable=True),
        sa.Column("entry_zone_high", sa.Float(), nullable=True),
        sa.Column("market_cap_usd", sa.Float(), nullable=True),
        sa.Column("liquidity_usd", sa.Float(), nullable=True),
        sa.Column("ai_recommendation", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_signals_token_mint_created_at", "signals", ["token_mint", "created_at"])

    op.create_table(
        "auto_trading_configs",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False, unique=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("fixed_trade_amount_usd", sa.Float(), nullable=True),
        sa.Column("percent_allocation", sa.Float(), nullable=True),
        sa.Column("max_slippage_bps", sa.Integer(), nullable=False, server_default="150"),
        sa.Column("max_market_cap_usd", sa.Float(), nullable=True),
        sa.Column("min_liquidity_usd", sa.Float(), nullable=False, server_default="10000"),
        sa.Column("stop_loss_percent", sa.Float(), nullable=True),
        sa.Column("take_profit_percent", sa.Float(), nullable=True),
        sa.Column("max_open_positions", sa.Integer(), nullable=False, server_default="5"),
        sa.Column("max_daily_trades", sa.Integer(), nullable=False, server_default="10"),
        sa.Column("max_daily_exposure_usd", sa.Float(), nullable=False, server_default="500"),
        sa.Column("token_blacklist", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False, server_default="15"),
        sa.Column("risk_profile", risk_profile_enum, nullable=False, server_default="BALANCED"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "trades",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("signal_id", sa.String(), sa.ForeignKey("signals.id"), nullable=True),
        sa.Column("source", trade_source_enum, nullable=False),
        sa.Column("side", trade_side_enum, nullable=False),
        sa.Column("token_mint", sa.String(), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column("amount_tokens", sa.Float(), nullable=True),
        sa.Column("status", trade_status_enum, nullable=False, server_default="PENDING"),
        sa.Column("tx_signature", sa.String(), nullable=True),
        sa.Column("slippage_bps", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        # NEW columns for restart-safe reconciliation (see PORTING_NOTES.md #3):
        sa.Column("last_blockhash", sa.String(), nullable=True),
        sa.Column("last_valid_block_height", sa.Integer(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciliation_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index("ix_trades_user_id_created_at", "trades", ["user_id", "created_at"])

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("actor_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("metadata", postgresql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_audit_logs_actor_id_created_at", "audit_logs", ["actor_id", "created_at"])


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("trades")
    op.drop_table("auto_trading_configs")
    op.drop_table("signals")
    op.drop_table("wallet_events")
    op.drop_index("ix_whale_wallets_score", table_name="whale_wallets")
    op.drop_index("ix_whale_wallets_status", table_name="whale_wallets")
    op.drop_table("whale_wallets")
    op.drop_table("users")

    bind = op.get_bind()
    for e in (
        trade_status_enum,
        trade_source_enum,
        trade_side_enum,
        risk_profile_enum,
        wallet_status_enum,
        role_enum,
    ):
        e.drop(bind, checkfirst=True)
