"""domain/trading/auto_trade/constants.py

Shared, dependency-free constants for the Auto-Trade Engine: rejection
reasons (§6) and default tuning values. Kept in its own module so
policy_service.py, risk_gate.py, and orchestrator.py can share it
without import cycles.
"""

DEFAULT_ETH_PER_TRADE = 0.01
DEFAULT_ETH_PER_TRADE = DEFAULT_ETH_PER_TRADE
DEFAULT_DAILY_TRADE_LIMIT = 5
DEFAULT_MAX_OPEN_POSITIONS = 5
DEFAULT_COOLDOWN_SECONDS = 120
BUY_NETWORK_RESERVE_WEI = 2_000_000_000_000_000  # ~0.002 ETH gas/fee reserve

SIGNAL_LOOKBACK_MINUTES = 20
CLAIM_RECONCILE_GRACE_SECONDS = 90


class RejectionReason:
    AUTO_TRADE_DISABLED = "AUTO_TRADE_DISABLED"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    SIGNAL_TIER_NOT_ALLOWED = "SIGNAL_TIER_NOT_ALLOWED"
    SIGNAL_TOO_OLD = "SIGNAL_TOO_OLD"
    SIGNAL_BEFORE_ACTIVATION = "SIGNAL_BEFORE_ACTIVATION"
    DAILY_LIMIT_REACHED = "DAILY_LIMIT_REACHED"
    MAX_OPEN_POSITIONS_REACHED = "MAX_OPEN_POSITIONS_REACHED"
    MAX_EXPOSURE_REACHED = "MAX_EXPOSURE_REACHED"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    POSITION_ALREADY_OPEN = "POSITION_ALREADY_OPEN"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    INVALID_TRADE_AMOUNT = "INVALID_TRADE_AMOUNT"
    EXECUTION_UNAVAILABLE = "EXECUTION_UNAVAILABLE"
    RISK_CHECK_FAILED = "RISK_CHECK_FAILED"
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    NO_WALLET = "NO_WALLET"


class ExecutionStatus:
    SUBMITTED = "submitted"
    CONFIRMED_SUCCESS = "confirmed_success"
    CONFIRMED_FAILURE = "confirmed_failure"
    UNKNOWN = "unknown"
