"""
hoodalpha/db.py

Two distinct data-access paths, on purpose:

1. `hood_session()` -- an async SQLAlchemy session bound to HoodAlpha's
   own ORM models (hoodalpha/models.py), all of which live in the
   `hoodalpha` Postgres schema. This is the ONLY path HoodAlpha ever
   writes through.

2. `fetch_delivered_signals()` / `fetch_current_prices()` -- read-only,
   hand-written parameterized SQL (SQLAlchemy `text()`) against
   WhaleAlpha's `public.signal_tokens` table. Deliberately NOT an
   import of `models.signal_token.SignalToken` or
   `infra.db.session.async_session` -- HoodAlpha never imports
   WhaleAlpha's Python modules, only reads its database, so a
   WhaleAlpha-side refactor of that ORM model cannot break HoodAlpha's
   import graph. The coupling that remains (column names in
   `signal_tokens`) is the exact, minimal coupling implied by "HoodAlpha
   should consume/read the relevant historical alert data generated by
   WhaleAlpha."

Both paths point at the SAME DATABASE_URL/Postgres instance. HoodAlpha
never issues INSERT/UPDATE/DELETE against anything outside the
`hoodalpha` schema.
"""

from __future__ import annotations

import logging

from sqlalchemy import text, bindparam
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase

from hoodalpha.settings import DATABASE_URL

logger = logging.getLogger("HoodAlpha.DB")

if not DATABASE_URL:
    raise ValueError(
        "DATABASE_URL is missing for HoodAlpha. Point it at the SAME "
        "Postgres instance WhaleAlpha uses (e.g. a Railway "
        "${{Postgres.DATABASE_URL}} reference variable on HoodAlpha's "
        "own services)."
    )

_url = DATABASE_URL
if _url.startswith("postgresql://"):
    _url = _url.replace("postgresql://", "postgresql+asyncpg://", 1)

# Deliberately small, separate pool from WhaleAlpha's engine -- these are
# two independent processes/services, each with their own connections to
# the same Postgres instance.
engine = create_async_engine(_url, echo=False, pool_pre_ping=True, pool_size=5, max_overflow=5)
hood_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


class HoodBase(DeclarativeBase):
    """Separate declarative base from WhaleAlpha's infra.db.session.Base
    -- HoodAlpha's models never register against WhaleAlpha's metadata
    (and therefore can never appear in WhaleAlpha's Alembic autogenerate
    diffs)."""
    pass


async def close_db() -> None:
    await engine.dispose()


# ---------------------------------------------------------------------
# Read-only access to WhaleAlpha's public.signal_tokens
# ---------------------------------------------------------------------

_SELECT_DELIVERED_SIGNALS = text(
    """
    SELECT id, contract, chain, symbol, name, entry_price, current_price, status
    FROM public.signal_tokens
    WHERE id > :after_id
      AND alert_delivered = true
      AND entry_price IS NOT NULL
      AND entry_price > 0
    ORDER BY id ASC
    LIMIT :limit
    """
)


async def fetch_delivered_signals(after_id: int, limit: int) -> list[dict]:
    """Rows from WhaleAlpha's signal_tokens where an alert was actually
    confirmed delivered to at least one subscriber (alert_delivered =
    true -- NOT just status == 'active', which is set at row-creation
    time before delivery is even attempted; see models/signal_token.py's
    own comments on that distinction)."""
    async with engine.connect() as conn:
        result = await conn.execute(_SELECT_DELIVERED_SIGNALS, {"after_id": after_id, "limit": limit})
        return [dict(row._mapping) for row in result]


_SELECT_CURRENT_PRICES = text(
    """
    SELECT contract, chain, current_price, status
    FROM public.signal_tokens
    WHERE contract IN :contracts
    """
).bindparams(bindparam("contracts", expanding=True))


async def fetch_current_prices(pairs: list[tuple[str, str]]) -> dict[tuple[str, str], dict]:
    """Piggybacks on WhaleAlpha's own signal_lifecycle_loop, which already
    polls DexScreener for every active signal every ~90s
    (domain/signals/signal_tracker.py::signal_lifecycle_loop). Returns
    {} for any (contract, chain) no longer present in signal_tokens
    (archived/deleted) -- callers fall back to hoodalpha/marketdata.py
    for those, per HOOD_FALLBACK_DEXSCREENER_ENABLED.

    Queries by `contract` alone (asyncpg has no clean composite-row IN
    binding), then filters/matches by `chain` in Python below --
    deliberately NOT trusting `contract` as a unique key by itself.
    WhaleAlpha's own signal_tokens.contract column is unique GLOBALLY
    today, not per (contract, chain), which is a latent multi-chain
    collision gap in that table. If a future WhaleAlpha change ever
    allows two rows with the same contract on different chains, a
    row whose chain doesn't match the pair we asked for is treated as
    "not found" here rather than silently matched -- see the chain
    check below.
    """
    if not pairs:
        return {}

    contracts = list({c for c, _ in pairs})

    async with engine.connect() as conn:
        result = await conn.execute(_SELECT_CURRENT_PRICES, {"contracts": contracts})
        by_contract: dict[str, list[dict]] = {}
        for row in result:
            m = dict(row._mapping)
            by_contract.setdefault(m["contract"], []).append(m)

    out: dict[tuple[str, str], dict] = {}
    for contract, chain in pairs:
        for candidate in by_contract.get(contract, []):
            if candidate["chain"] == chain:
                out[(contract, chain)] = candidate
                break
    return out
